function test_text_prompt_build_readiness()
% Text-only prompts with complete topology should remain build-ready.

spec = struct();
spec.circuit_type = "text-described RC low-pass";
spec.components = struct( ...
    "id", {"R1", "C1"}, ...
    "type", {"resistor", "capacitor"}, ...
    "label", {"R1", "C1"}, ...
    "value", {39800, 1e-7}, ...
    "unit", {"ohm", "F"}, ...
    "terminals", {{"p", "n"}, {"p", "n"}}, ...
    "confidence", {0.99, 0.99});
spec.nodes = ["n_in", "n_out", "gnd"];
spec.connections = struct( ...
    "from", {"R1.p", "R1.n", "C1.p", "C1.n"}, ...
    "to", {"n_in", "n_out", "n_out", "gnd"}, ...
    "label", {"input", "output", "cap top", "cap bottom"}, ...
    "confidence", {0.99, 0.99, 0.99, 0.99});
spec.ground_node = "gnd";
spec.sources = struct([]);
spec.requested_outputs = "Vout";
spec.likely_analysis = "time-domain transient";
spec.assumptions = "Topology inferred from text prompt.";
spec.ambiguities = "No image was attached; topology is inferred from the text prompt.";
spec.unsupported_or_unclear_regions = [
    "No visible circuit diagram was provided for independent verification of node layout or symbol orientation."
    "No attached image was provided; topology is inferred entirely from the text prompt."
    "No details are given for the ECG sensor source impedance or electrode front-end behavior."
];
spec.suggested_simscape_blocks = ["Resistor", "Capacitor", "Electrical Reference"];
spec.focus_points = struct([]);

readiness = citt.classifyBuildReadiness(spec);
assert(readiness.build_ready, "Text prompt with complete topology should be build-ready.");
assert(contains(readiness.nonblocking_text, "No visible circuit diagram"), ...
    "No-image note should be preserved as a non-blocking note.");
assert(contains(readiness.nonblocking_text, "source impedance"), ...
    "Source-impedance note should be preserved as a non-blocking note.");

pkSpec = spec;
pkSpec.circuit_type = "PK-driven electrochemical biosensor front end";
pkSpec.components = struct( ...
    "id", {"C_PK_SOURCE", "H_MEMBRANE_LAG", "G_SENSOR_SENS", "U_TIA", "ADC_12"}, ...
    "type", {"signal_source", "first_order_lag", "controlled_gain", "operational_amplifier", "analog_to_digital_converter"}, ...
    "label", {"PK concentration input", "membrane mass-transfer lag", "25 nA/uM sensor gain", "TIA", "12-bit ADC"}, ...
    "value", {"parameters unspecified", 4, 25, "generic", 12}, ...
    "unit", {"uM", "s", "nA/uM", "", "bits"}, ...
    "terminals", {{"out"}, {"in", "out"}, {"in", "out"}, {"inverting", "output"}, {"analog_in", "digital_out"}}, ...
    "confidence", {0.95, 0.98, 0.98, 0.9, 0.9});
pkSpec.nodes = ["N_C_PK", "N_C_LAG", "N_SENSOR_CURRENT", "N_TIA_OUT", "N_ADC_CODE"];
pkSpec.connections = struct( ...
    "from", {"C_PK_SOURCE.out", "H_MEMBRANE_LAG.out", "G_SENSOR_SENS.out", "U_TIA.output"}, ...
    "to", {"N_C_PK", "N_C_LAG", "N_SENSOR_CURRENT", "N_TIA_OUT"}, ...
    "label", {"PK input", "lagged concentration", "sensor current", "TIA output"}, ...
    "confidence", {0.95, 0.95, 0.95, 0.95});
pkSpec.requested_outputs = ["concentration", "sensor current", "TIA output", "ADC saturation"];
pkSpec.assumptions = "Omitted PK and ADC values remain visible teaching parameters.";
pkSpec.ambiguities = [
    "One-compartment oral PK parameters are not specified."
    "ADC reference voltage, input range, sampling rate, and coding format are not specified."
];
pkSpec.unsupported_or_unclear_regions = [
    "No visible diagram was provided, so there are no image regions to verify against the prompt."
    "Noise model details for the TIA bandwidth/noise tradeoff are not specified enough for a unique quantitative noise implementation."
];

readiness = citt.classifyBuildReadiness(pkSpec);
assert(readiness.build_ready, "Cross-domain prompt with a clear signal chain should build with explicit defaults.");
assert(contains(readiness.nonblocking_text, "No visible diagram"), ...
    "No-diagram note should be non-blocking.");
assert(contains(readiness.nonblocking_text, "Noise model details"), ...
    "Qualitative noise-model boundary should be non-blocking and visible as a modeling assumption.");
end
