function manifest = loadManifest(labId)
%LOADMANIFEST Load CiTT playground manifest from API or built-in fallback.

if nargin < 1 || strlength(string(labId)) == 0
    labId = "rc_antialias_adc";
end

apiUrl = "http://127.0.0.1:8000/matlab_playground/manifest";
try
    options = weboptions("Timeout", 2);
    manifest = webread(apiUrl, options);
    return
catch apiError
    warning("CiTT:ManifestFallback", ...
        "Backend manifest unavailable (%s). Loading built-in offline manifest.", apiError.message);
end

manifest = builtinManifest(string(labId));
end

function manifest = builtinManifest(labId)
manifest = struct();
manifest.product_name = "CiTT MATLAB/Simscape Playground";
manifest.version = "1.0.0";
manifest.positioning = "Graphical tutor layer for BME circuits and signal-conditioning labs.";
manifest.tabs = ["overview", "teach", "probe", "lab_delta"];
manifest.labs = [ ...
    struct("id", "rc_antialias_adc", ...
        "title", "RC anti-aliasing filter before ADC", ...
        "summary", "ECG-like signal, RC low-pass filtering, sampling, probes, and Lab Delta.", ...
        "bme_context", "Signal-conditioning before ADC sampling."), ...
    struct("id", "instrumentation_amplifier_feedback", ...
        "title", "Instrumentation amplifier feedback focus", ...
        "summary", "Differential/common-mode input, gain setting, feedback-loop highlight, and output probe.", ...
        "bme_context", "ECG instrumentation front-end teaching path.") ...
    ];
manifest.focus_map = builtinFocusMap(labId);
manifest.probe_plans = builtinProbePlans(labId);
manifest.notes = ["Offline fallback manifest", "Use API refresh when the FastAPI backend is running"];
end

function focusMap = builtinFocusMap(labId)
if labId == "instrumentation_amplifier_feedback"
    focusMap = [ ...
        focusEntry("differential_input", "Differential input", "Differential signal at the two input ports."), ...
        focusEntry("common_mode_input", "Common-mode input", "Shared input signal to reject."), ...
        focusEntry("gain_setting_resistor", "Gain-setting resistor", "Resistor that sets instrumentation amplifier gain."), ...
        focusEntry("feedback_loop", "Feedback loop", "Output-to-inverting-input loop to highlight."), ...
        focusEntry("op_amp_output", "Op-amp output", "Output node for gain and saturation checks."), ...
        focusEntry("output_probe", "Output probe", "Lab Delta measurement point.") ...
    ];
else
    focusMap = [ ...
        focusEntry("overview_signal_flow", "Overview signal flow", "Input, RC filter, sampler, and output."), ...
        focusEntry("input_path", "Input path", "ECG-like input plus interference."), ...
        focusEntry("rc_filter", "RC filter", "Resistor and capacitor cutoff region."), ...
        focusEntry("capacitor_output_node", "Capacitor output node", "Voltage across C before sampling."), ...
        focusEntry("sampling_stage", "Sampling stage", "ADC/sample boundary."), ...
        focusEntry("output_signal", "Output signal", "Sampled output trace."), ...
        focusEntry("lab_delta_measurement_point", "Lab Delta measurement point", "Scope/data alignment point.") ...
    ];
end
end

function entry = focusEntry(id, label, description)
entry = struct();
entry.id = id;
entry.label = label;
entry.mode = "teach";
entry.description = description;
entry.targets = struct("id", id, "label", label, "target_type", "conceptual_path", ...
    "model_path", "", "style", "default", "reason", description);
entry.student_prompt = "";
end

function probePlans = builtinProbePlans(labId)
if labId == "instrumentation_amplifier_feedback"
    probePlans = [ ...
        probePlan("differential_input_probe", "Differential input probe", "citt_v_diff"), ...
        probePlan("feedback_loop_probe", "Feedback loop highlight probe", "citt_feedback_loop_focus"), ...
        probePlan("output_voltage_probe", "Output voltage probe", "citt_inamp_output") ...
    ];
else
    probePlans = [ ...
        probePlan("input_signal_probe", "Input signal probe", "citt_input_signal"), ...
        probePlan("filter_output_voltage_probe", "Filter output voltage probe", "citt_filtered_signal"), ...
        probePlan("sampled_output_probe", "Sampled output probe", "citt_sampled_signal"), ...
        probePlan("cutoff_attenuation_check", "Cutoff and attenuation check", "citt_hand_fc_hz") ...
    ];
end
end

function plan = probePlan(id, label, variableName)
plan = struct();
plan.id = id;
plan.label = label;
plan.measurement_type = "voltage or signal";
plan.expected_unit = "V";
plan.matlab_variable_name = variableName;
plan.student_question = "What should this probe make visible?";
end
