function app = citt(labId)
%CITT Open the CiTT graphical MATLAB/Simscape tutor popup.
% Students use this popup and the CiTT web UI; generated MATLAB/Simscape
% setup remains behind buttons.

if nargin < 1 || strlength(string(labId)) == 0
    labId = "rc_antialias_adc";
end

manifest = citt.loadManifest(labId);
app = struct();
app.Manifest = manifest;
app.LabId = string(labId);
app.Figure = uifigure( ...
    "Name", "CiTT MATLAB/Simscape Tutor", ...
    "Position", [100 100 1040 700]);
tabs = uitabgroup(app.Figure, "Position", [12 12 1016 676]);

overviewTab = uitab(tabs, "Title", "Overview");
teachTab = uitab(tabs, "Title", "Teach");
probeTab = uitab(tabs, "Title", "Probe");
deltaTab = uitab(tabs, "Title", "Lab Delta");

uilabel(overviewTab, ...
    "Text", "CiTT keeps students in a graphical tutor while MATLAB, Simulink, and Simscape provide the engineering playground.", ...
    "Position", [24 600 920 32]);
uilabel(overviewTab, ...
    "Text", "The internal solver remains the hand-check and fallback verifier.", ...
    "Position", [24 568 720 26]);
uibutton(overviewTab, ...
    "Text", "Build MATLAB/Simscape Playground", ...
    "Position", [24 512 260 34], ...
    "ButtonPushedFcn", @(~, ~) citt.buildPlayground(labId));
uibutton(overviewTab, ...
    "Text", "Run Hand Check", ...
    "Position", [300 512 150 34], ...
    "ButtonPushedFcn", @(~, ~) disp(citt.buildPlayground(labId).hand_check));

uilabel(teachTab, ...
    "Text", "Teach mode maps guided lesson steps to circuit/model focus targets.", ...
    "Position", [24 600 760 32]);
uibutton(teachTab, ...
    "Text", "Highlight Current Step", ...
    "Position", [24 540 190 34], ...
    "ButtonPushedFcn", @(~, ~) citt.highlightFocus("", manifest.focus_map, "rc_filter"));
uibutton(teachTab, ...
    "Text", "Highlight Feedback Loop", ...
    "Position", [230 540 200 34], ...
    "ButtonPushedFcn", @(~, ~) citt.highlightFocus("", manifest.focus_map, "feedback_loop"));

uilabel(probeTab, ...
    "Text", "Probe mode recommends voltage/current/signal measurements and logging names.", ...
    "Position", [24 600 820 32]);
uibutton(probeTab, ...
    "Text", "Add Probe Plan", ...
    "Position", [24 540 160 34], ...
    "ButtonPushedFcn", @(~, ~) disp("CiTT probe plan selected from manifest.probe_plans."));

uilabel(deltaTab, ...
    "Text", "Lab Delta compares hand calculation, generated simulation evidence, and measured lab data.", ...
    "Position", [24 600 850 32]);
uibutton(deltaTab, ...
    "Text", "Compare Lab Delta", ...
    "Position", [24 540 180 34], ...
    "ButtonPushedFcn", @(~, ~) citt.runLabDelta(labId));
end
